CREATE SEQUENCE IF NOT EXISTS hibernate_sequence START WITH 1 INCREMENT BY 1;
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Cinnamon Buns Sticky', 257.45);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Pail With Metal Handle 16l White', 951.39);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Scotch - Queen Anne', 172.75);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Capon - Whole', 961.58);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Chicken - Base', 973.79);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Appetizer - Spring Roll, Veg', 565.83);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Wine - Blue Nun Qualitatswein', 56.28);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Marjoram - Dried, Rubbed', 793.63);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Flour - Semolina', 68.65);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Lumpfish Black', 12.05);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Mussels - Cultivated', 95.14);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Cherries - Bing, Canned', 15.29);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Wine - Red, Concha Y Toro', 473.05);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Pineapple - Golden', 188.06);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Fenngreek Seed', 769.94);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'General Purpose Trigger', 790.97);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Cheese - Sheep Milk', 313.94);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Onion Powder', 78.28);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Rambutan', 911.64);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Grenadillo', 364.57);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Chouta', 2.57);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Ruina Oscura', 1264.57);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Musgo Ardiente', 10.57);